[build]
  command = "pip install poetry && poetry install --no-root && poetry run python codeforher_backend/api.py"
  publish = "."
  
[context.production.environment]
  PYTHON_VERSION = "3.12"  # or your preferred Python version
  PORT = "8080"
  PYTHONPATH = "/opt/build/repo"
