[build]
  command = "pip install -r requirements.txt"
  publish = "codeforher_backend/api.py"
  
[context.production.environment]
  PYTHON_VERSION = "3.12"  # or your preferred Python version
  PORT = "8080"
  PYTHONPATH = "/opt/build/repo"
