[build]
  command = "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
  publish = "."
  
[context.production.environment]
  PYTHON_VERSION = "3.12"  # or your preferred Python version
  PORT = "8080"
